package com.dairy.dairy_management.service;

import com.dairy.dairy_management.dto.BulkBillResult;
import com.dairy.dairy_management.dto.GenerateDeliveryResult;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.time.YearMonth;

/**
 * Scheduled background jobs for the dairy management system.
 *
 * Job 1 — Daily delivery generation:
 *   Runs at 05:00 AM every day.
 *   Generates delivery records for all active subscriptions.
 *   Idempotent — safe to re-run if the job fails and is retried manually.
 *
 * Job 2 — Monthly billing:
 *   Runs at 02:00 AM on the 1st of each month.
 *   Generates bills for ALL active customers for the previous month.
 *   Admin can still regenerate individual bills manually at any time.
 *
 * Manual trigger (admin):
 *   POST /deliveries/generate?date=        → manual delivery generation
 *   POST /billing/generate-all?month=&year= → manual bulk billing
 */
@Service
public class ScheduledJobService {

    private static final Logger log = LoggerFactory.getLogger(ScheduledJobService.class);

    private final DeliveryService deliveryService;
    private final BillingService billingService;
    private final AuditLogService auditLogService;

    public ScheduledJobService(DeliveryService deliveryService,
                               BillingService billingService,
                               AuditLogService auditLogService) {
        this.deliveryService = deliveryService;
        this.billingService = billingService;
        this.auditLogService = auditLogService;
    }

    /**
     * Automatically generates delivery records every morning at 5:00 AM.
     *
     * Respects holidays and delivery overrides configured by admin.
     * Cron: second=0, minute=0, hour=5, day=*, month=*, weekday=*
     */
    @Scheduled(cron = "0 0 5 * * *")
    public void autoGenerateDeliveries() {
        LocalDate today = LocalDate.now();
        log.info("[SCHEDULER] Starting daily delivery generation for {}", today);

        try {
            GenerateDeliveryResult result = deliveryService.generateForDate(today);
            String details = String.format(
                    "Date=%s | Generated=%d | AlreadyExisted=%d | Skipped=%d",
                    today, result.getCreated(),
                    result.getAlreadyExisted(), result.getNotScheduled());

            log.info("[SCHEDULER] Delivery generation complete: {}", details);
            auditLogService.log("AUTO_DELIVERY_GENERATED", "DELIVERY", null, details);

        } catch (Exception e) {
            log.error("[SCHEDULER] Delivery generation FAILED for {}: {}", today, e.getMessage(), e);
            auditLogService.log("AUTO_DELIVERY_GENERATED", "DELIVERY", null,
                    "FAILED for " + today + ": " + e.getMessage());
        }
    }

    /**
     * Automatically generates bills for all active customers on the 1st of each month at 2:00 AM.
     *
     * Generates bills for the PREVIOUS month (because on March 1st, February is complete).
     * Cron: second=0, minute=0, hour=2, day=1, month=*, weekday=*
     */
    @Scheduled(cron = "0 0 2 1 * *")
    public void autoGenerateMonthlyBills() {
        YearMonth previousMonth = YearMonth.now().minusMonths(1);
        int month = previousMonth.getMonthValue();
        int year = previousMonth.getYear();

        log.info("[SCHEDULER] Starting bulk bill generation for {}/{}", month, year);

        try {
            BulkBillResult result = billingService.generateAllBills(month, year);
            String details = String.format(
                    "Month=%d/%d | Generated=%d | Skipped=%d | Errors=%d",
                    month, year, result.getBillsGenerated(),
                    result.getBillsSkipped(), result.getErrors().size());

            log.info("[SCHEDULER] Bulk billing complete: {}", details);
            auditLogService.log("AUTO_BILL_GENERATED", "BILLING", null, details);

        } catch (Exception e) {
            log.error("[SCHEDULER] Bulk billing FAILED for {}/{}: {}", month, year, e.getMessage(), e);
            auditLogService.log("AUTO_BILL_GENERATED", "BILLING", null,
                    "FAILED for " + month + "/" + year + ": " + e.getMessage());
        }
    }
}
