spring.application.name=dairy-management
spring.datasource.url=jdbc:postgresql://localhost:5432/dairy_db
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect