spring.application.name=dairy-management
spring.datasource.url=jdbc:postgresql://localhost:5432/dairy_db
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=shivaay-dairy-management-secret-key-2024-very-long-secure-string-minimum-256-bits
jwt.expiration=86400000
# Refresh token lives 7 days
jwt.refresh-expiration=604800000